allowBuilds:
  esbuild: true
  google-ads-node@https://codeload.github.com/skyriseltd/google-ads-node/tar.gz/e5bccf0dab077b704cbe3d70c05a43d34c84b354: true
  protobufjs: true
minimumReleaseAge: 0
overrides:
  '@skyriseltd/google-ads-api': 'link:'
